# Default values for fluentd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: prod-nexus.web.s7.ru:7018/fluentd-custom-164
  pullPolicy: IfNotPresent
  
serviceAccount:
  create: true

secret_nexus_auth:
  name: "nexus-auth-wsp"
  auth_cert:
    .dockerconfigjson: eyJhdXRocyI6eyJwcm9kLW5leHVzLndlYi5zNy5ydTo3MDE4Ijp7ImF1dGgiOiJhemh6WDNCMWJHeGZkM053T2tsSWN6aFJjRE0wYUZSTlVRPT0ifX19Cg==

initContainers:
  volumeMounts:
    - name: config-path
      mountPath: /usr/share/fluentd/
    - name: config-source
      mountPath: /usr/share/fluentd/etc/
    - name: config-all
      mountPath: /usr/share/fluentd/etc/config.d/
    - name: all-path
      mountPath: /usr/share/fluentd/etc/all/

volumeMounts:
  - name: config-path
    mountPath: /usr/share/fluentd/
  - name: all-path
    mountPath: /usr/share/fluentd/etc/all/
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true

volumes:
  - name: config-source
    configMap:
      name: fluentd-conf
  - name: config-all
    configMap:
      name: fluentd-all
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: config-path
    emptyDir: {}
  - name: all-path
    emptyDir: {}
